version: '2.3'
services:
  object-detection:
    image: bscppc/class-object-detection
    runtime: nvidia
    ports:
      - "${TKDNN_PORT}:${TKDNN_PORT}/tcp"
      - "${TKDNN_PORT}:${TKDNN_PORT}/udp"
    tty: true
    network_mode: bridge
    environment:
      - TKDNN_PORT=${TKDNN_PORT}
      - CAM_ID=${CAM_ID}
    command: bash -c "cd class-edge/ && cd build && make -j8 && cd tkDNN/ && ./demo 1 ${CAM_ID} ${TKDNN_PORT} 2500 0 1 <<< 'class' & exec bash"
