version: '3.4'
services:
  logicmodule:
    image: "bscppc/dataclay-logicmodule"
    command: "${COMMAND_OPTS}"
    ports:
      - "11034:11034"
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - EXPOSED_IP_FOR_CLIENT=192.168.7.32
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/home/dataclayusr/dataclay/logging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
         
  dsjava:
    image: "bscppc/dataclay-dsjava"
    command: "${COMMAND_OPTS}"
    ports:
      - "2127:2127"
    depends_on:
      - logicmodule
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
      - ./prop/log4j2.xml:/home/dataclayusr/dataclay/logging/log4j2.xml:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
  dspython:
    image: "bscppc/dataclay-dspython"
    command: "${COMMAND_OPTS}"
    ports:
      - "6867:6867"
    depends_on:
      - logicmodule
      - dsjava
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - DEBUG=True
    volumes:
      - ./prop/global.properties:/home/dataclayusr/dataclay/cfgfiles/global.properties:ro
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
