version: '3.5'
volumes:
  dataclay-init:
    driver: local
services:
  logicmodule:
    image: "bscdataclay/logicmodule:dev20210422-alpine"
    command: ""
    volumes:
      - type: bind
        source: /tmp/dataClay-cloud/storage
        target: /dataclay/storage
    ports:
      - "11034:11034"
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - DATACLAY_ADMIN_USER=admin
      - DATACLAY_ADMIN_PASSWORD=admin
      - EXPOSED_IP_FOR_CLIENT=192.168.7.32
    deploy:
     resources:
       limits:
         memory: 1024M
       reservations:
	    memory: 250M
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
         
  dsjava:
    image: "bscdataclay/dsjava:dev20210422-alpine"
    command: ""
    volumes:
      - type: bind
        source: /tmp/dataClay-cloud/storage
        target: /dataclay/storage
    ports:
      - "2127:2127"
    depends_on:
      - logicmodule
    environment:
      - DATASERVICE_NAME=DS1
      - DATASERVICE_JAVA_PORT_TCP=2127
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - GLOBALGC_COLLECTOR_INITIAL_DELAY_HOURS=0
      - GLOBALGC_MAX_TIME_QUARANTINE=200
      # GLOBALGC_COLLECT_TIME_INTERVAL -> # of ms when unreferenced objects are deleted from db
      - GLOBALGC_COLLECT_TIME_INTERVAL=120000
      - GLOBALGC_CHECK_REMOTE_PENDING=4000
      - GLOBALGC_PROCESS_COUNTINGS_INTERVAL=2000
      - GLOBALGC_MAX_OBJECTS_TO_COLLECT_ITERATION=1000
      - MEMMGMT_CHECK_TIME_INTERVAL=60000
      - MEMMGMT_PRESSURE_FRACTION=0.75
      - MEMMGMT_MIN_OBJECT_TIME=200
    deploy:
     resources:
       limits:
         memory: 1024M
       reservations:
         memory: 250M
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]
       
  dspython:
    image: "bscdataclay/dspython:dev20210422.py36-slim"
    command: ""
    volumes:
      - type: bind
        source: /tmp/dataClay-cloud/storage
        target: /dataclay/storage
    ports:
      - "6867:6867"
    depends_on:
      - logicmodule
      - dsjava
    environment:
      - DATASERVICE_NAME=DS1
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - PYCLAY_LIBS=requests geolib pygeohash numpy
      - DATASERVICE_PYTHON_PORT_TCP=6867
      - MEMMGMT_CHECK_TIME_INTERVAL=60000
      - MEMMGMT_PRESSURE_FRACTION=0.75
      - MEMMGMT_MIN_OBJECT_TIME=200
      - MEMMGMT_EASE_FRACTION=0.0
      #- LOGLEVEL=TRACE
    deploy:
     resources:
       limits:
         memory: 2048M
       reservations:
         memory: 100M
    stop_grace_period: 5m
    healthcheck:
       interval: 5s
       retries: 10
       test: ["CMD-SHELL", "/home/dataclayusr/dataclay/health/health_check.sh"]

  dcinitializer:
    image: "bscdataclay/initializer:dev20210422-alpine"
    depends_on:
      - logicmodule
    command: "--wait-for-python-ds 1 --wait-for-java-ds 1"
    volumes:
      - dataclay-init:/srv/dataclay/shared
      - ./model/:/model/:ro
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - USER=CityUser
      - PASS=p4ssw0rd
      - DATASET=City
      - PYTHON_MODELS_PATH=/model/src
      - PYTHON_NAMESPACES=CityNS
    healthcheck:
      interval: 5s
      retries: 10
      test: [ "CMD-SHELL", "/dataclay-initializer/health_check.sh" ]

  retrieve-objects:
    image: retrieve-objects
    build: retrieve-objects
    depends_on:
      - dcinitializer
    volumes:
      - dataclay-init:/srv/dataclay/shared:ro
    environment:
      - LOGICMODULE_PORT_TCP=11034
      - LOGICMODULE_HOST=logicmodule
      - USER=CityUser
      - PASS=p4ssw0rd
      - DATASET=City
      - NAMESPACE=CityNS
